services:
  dev-db:
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=nestjs-prisma-e2e-test
  test-db:
    image: postgres:latest
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=nestjs-prisma-e2e-test
